export const booksData = [
    {
      id: 1,
      title: "The Great Gatsby",
      author: "F. Scott Fitzgerald",
      rating: "4.5",
      category: "Fiction",
      description: "A story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan.",
      image: "https://m.media-amazon.com/images/I/61dRoDRubtL._SL1500_.jpg",
    },
    {
      id: 2,
      title: "To Kill a Mockingbird",
      author: "Harper Lee",
      rating: "4.2",
      category: "Fiction",
      description: "A powerful story of racial injustice and the loss of innocence in the American South.",
      image: "https://books.google.com/books/content?id=PGR2AwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    },
    {
      id: 3,
      title: "1984",
      author: "George Orwell",
      rating: "3.5",
      category: "Science Fiction",
      description: "A dystopian novel about totalitarianism and the dangers of a surveillance state.",
      image: "https://tse2.mm.bing.net/th?id=OIP.uQJtTFPb-YFRkyScGmSTfQHaLJ&pid=Api&P=0&h=220",
    },
    {
      id: 4,
      title: "Pride and Prejudice",
      author: "Jane Austen",
      rating: "4",
      category: "Romance",
      description: "A romantic novel of manners that satirizes the British landed gentry.",
      image: "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p468777_b_v10_bo.jpg",
    
    },
    {
      id: 5,
      title: "The Catcher in the Rye",
      author: "J.D. Salinger",
      rating: "4.3",
      category: "Fiction",
      description: "A story of teenage rebellion and alienation.",
      image: "https://m.media-amazon.com/images/I/61ln1F2aMTL._SL1360_.jpg",
    },
    {
      id: 6,
      title: "The Hobbit",
      author: "J.R.R. Tolkien",
      rating: "2.5",
      category: "Fantasy",
      description: "A fantasy novel about the adventures of Bilbo Baggins.",
      image: "https://www.filmofilia.com/wp-content/uploads/2012/09/The-Hobbit_04.jpg",
    },
    {
      id: 7,
      title: "Fahrenheit 451",
      author: "Ray Bradbury",
      rating: "4.5",
      category: "Science Fiction",
      description: "A dystopian novel about a future society where books are banned.",
      image: "https://loresumo.com/wp-content/uploads/2019/07/fahrenheit-451-1.jpg",
    },
    {
      id: 8,
      title: "Moby-Dick",
      author: "Herman Melville",
      rating: "3.5",
      category: "Adventure",
      description: "A novel about the voyage of the whaling ship Pequod.",
      image: "https://books.google.com/books/content?id=5fBmDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    },
    {
      id: 9,
      title: "War and Peace",
      author: "Leo Tolstoy",
      rating: "4.3",
      category: "Historical Fiction",
      description: "A novel that intertwines the lives of individuals with historical events.",
      image: "https://books.google.com/books/content?id=5fBmDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    },
    {
      id: 10,
      title: "The Odyssey",
      author: "Homer",
      rating: "3.8",
      category: "Classic",
      description: "An epic poem about the journey of Odysseus.",
      image: "https://books.google.com/books/content?id=5fBmDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    },
    {
      id: 11,
      title: "The Alchemist",
      author: "Paulo Coelho",
      rating: "4.1",
      category: "Philosophical Fiction",
      description: "A novel about a young shepherd's journey to find treasure.",
      image: "https://books.google.com/books/content?id=5fBmDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    },
    {
      id: 12,
      title: "The Little Prince",
      author: "Antoine de Saint-Exupéry",
      rating: "4.2",
      category: "Children's Literature",
      description: "A poetic tale about a young prince who travels the universe.",
      image: "https://books.google.com/books/content?id=5fBmDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    },
    {
      id: 13,
      title: "The Book Thief",
      author: "Markus Zusak",
      rating: "4.9",
      category: "Historical Fiction",
      description: "A story of a young girl living in Nazi Germany who steals books.",
      image: "https://books.google.com/books/content?id=5fBmDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    },
    {
      id: 14,
      title: "The Kite Runner",
      author: "Khaled Hosseini",
      rating: "3.6",
      category: "Fiction",
      description: "A story of friendship, betrayal, and redemption in Afghanistan.",
      image: "https://www.bookishelf.com/wp-content/uploads/2020/02/Book-Review-The-Kite-Runner-by-Khaled-Hosseini.jpg",
    },
    {
      id: 15,
      title: "The Da Vinci Code",
      author: "Dan Brown",
      rating: "4.5",
      category: "Thriller",
      description: "A mystery thriller that explores the secrets of the Holy Grail.",
      image: "https://books.google.com/books/content?id=5fBmDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    },
    {
      id: 16,
      title: "The Shining",
      author: "Stephen King",
      rating: "4.1",
      category: "Horror",
      description: "A horror novel about a family's stay at a haunted hotel.",
      image: "https://books.google.com/books/content?id=5fBmDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    },
    {
      id: 17,
      title: "The Road",
      author: "Cormac McCarthy",
      rating: "4.2",
      category: "Post-Apocalyptic",
      description: "A post-apocalyptic novel about a father and son's journey.",
      image: "https://books.google.com/books/content?id=5fBmDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    },
    {
      id: 18,
      title: "The Handmaid's Tale",
      author: "Margaret Atwood",
      rating: "3.5",
      category: "Dystopian",
      description: "A dystopian novel about a totalitarian society.",
      image: "https://books.google.com/books/content?id=5fBmDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    },
    
    {
          id: 19,
          title: "Sapiens: A Brief History of Humankind",
          author: "Yuval Noah Harari",
          rating: "2.5",
          category: "Non-Fiction",
          description: "An exploration of the history of humanity, from the Stone Age to modern society.",
          image: "https://m.media-amazon.com/images/I/713jIoMO3UL.jpg"
        },
        {
          id: 20,
          title: "Becoming",
          author: "Michelle Obama",
          rating: "4.5",
          category: "Non-Fiction",
          description: "The memoir of Michelle Obama, chronicling her journey from childhood to the White House.",
          image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1612402901i/56786139.jpg"
        },
        {
          id: 21,
          title: "Educated",
          author: "Tara Westover",
          rating: "4.3",
          category: "Non-Fiction",
          description: "A memoir about growing up in a strict and abusive household in rural Idaho and pursuing education.",
          image: "https://academiamag.com/wp-content/uploads/2018/12/EDUCATED.jpg"
        },
        {
         id: 22,
         title: "The Power of Habit",
         author: "Charles Duhigg",
         rating: "4.2",
         category: "Non-Fiction",
         description: "A look at the science of habit formation and how habits shape our lives.",
         image: "https://media.npr.org/assets/bakertaylor/covers/t/the-power-of-habit/9781400069286_custom-401a0d258f36abc0afccb673d3bab1de7926e20e-s6-c30.jpg"
        },
        {
            id: 23,
            title: "Ender's Game",
            author: "Orson Scott Card",
            rating: "4.2",
            category: "Science Fiction",
            description: "A story about a young genius, Ender Wiggin, trained in a futuristic military school to fight an alien threat.",
            image: "https://www.pluggedin.com/wp-content/uploads/2020/01/enders-game-cover.jpg"
        },
        {
            id: 24,
            title:  "Dune",
            author:  "Frank Herbert",
            rating: "4.2",
            category: "Science Fiction",
            description: "A groundbreaking epic set in a desert world, exploring politics, religion, and humanity's relationship with nature.",
            image:  "https://books.google.com/books/content?id=B1BODwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"

        }
        
      ]
      
